### PR TITLE
Fix updating mysql hosts in proxysql for one node cluster

### PR DESCRIPTION
**Pull request by pservit**

### CODE REVIEW

**Comment by it-percona** [comment]
[CLA assistant check](https://cla-assistant.percona.com:443/Percona-Lab/percona-openshift?pullRequest=68) <br/>All committers have signed the CLA.

**Comment by dAdAbird** [comment]
Hi @pservit 
Thank you for your contribution. 
Can you elaborate more on how this change helps with the one node cluster? I don't get why peers list should be reset on lookup error. 

Thanks!

**Comment by pservit** [comment]
Hi Andrew,

when single pod in cluster restarted, list of peers not changed
so peer-list not calling onchange script and not updating list of servers in proxysql

during update kubernetes service without endpoints not resolved, so we have this behaviour:

["cluster1-pxc-0"]
...
resolv error
...
["cluster1-pxc-0"]

**Comment by dAdAbird** [comment]
Ok, yes, I see.
Can we check if the resolver error is `DNSError` (https://pkg.go.dev/net?tab=doc#DNSError) and `IsNotFound ` and flush peers only in that case?

**Comment by pservit** [comment]
Maybe, but I don't know if there is other cases we can miss service change during dns errors.
I think best way is to check list of endpoint ip addresses, not names.

**Comment by dAdAbird** [comment]
IP addresses won't work. We don't know on which addresses k8s will schedule and reschedule pods.

Let's try to check for `DNSError. IsNotFound `.
I'm just not feeling safe with flushing of the peers' list on any resolver error. Since it may trigger unnecessary calls of the script even if nothing changed but some network error happened.

**Comment by pservit** [comment]
> IP addresses won't work. We don't know on which addresses k8s will schedule and reschedule pods.

MySQL servers added to ProxySQL config as ip addresses, not dns names. So I think we should monitor changes of ip addresses. 

Example: 
1. we have nodes [cluster1-pxc-0, cluster1-pxc-1, cluster1-pxc-2].
2. cluster1-pxc-2 rescheduled to another k8s node
3. we again have cluster [cluster1-pxc-0, cluster1-pxc-1, cluster1-pxc-2], so list of servers not changed but ip of cluster1-pxc-2 changed

> Let's try to check for `DNSError. IsNotFound `.

Can you guide me how to do it? I'm not so good in Go - just read "Introducing Go" book yesterday :)

> I'm just not feeling safe with flushing of the peers' list on any resolver error. Since it may trigger unnecessary calls of the script even if nothing changed but some network error happened.

**Comment by dAdAbird** [comment]
> Can you guide me how to do it? I'm not so good in Go - just read "Introducing Go" book yesterday :)

Sure thing. You need type assertion https://golang.org/ref/spec#Type_assertions
Basically should be something like 
```go
if err != nil {
	if lerr, ok := err.(*net.DNSError); ok && lerr.IsNotFound {
		peers = sets.NewString()
	}
...
}
```
But, please, check if it works (net.Lookup does return DNSError with IsNotFound in case of no peers found)

**Comment by dAdAbird** [comment]
> MySQL servers added to ProxySQL config as ip addresses, not dns names. So I think we should monitor changes of ip addresses.

Yes, but IP addresses being added to the ProxySQL with this script :)

**Comment by pservit** [comment]
> But, please, check if it works (net.Lookup does return DNSError with IsNotFound in case of no peers found)

Checked - it works, thank you

**Comment by pservit** [comment]
> > MySQL servers added to ProxySQL config as ip addresses, not dns names. So I think we should monitor changes of ip addresses.
> 
> Yes, but IP addresses being added to the ProxySQL with this script :)

Yes, but onChange script called only when list of dns names changed, not ip addresses this names resolves to.

**Review by dAdAbird — APPROVED** [review]
LGTM
Thanks for your contribution!

**Comment by tplavcic** [comment]
@pservit Can you share more details on how to reproduce the issue you are facing, because I'm a bit confused.
You mention that mysql servers are entered into proxysql with IP addresses, but what I see is hostnames.
```
mysql> select * from mysql_servers;
+--------------+---------------------------------------------------+------+-----------+--------+--------+-------------+-----------------+---------------------+---------+----------------+---------+
| hostgroup_id | hostname                                          | port | gtid_port | status | weight | compression | max_connections | max_replication_lag | use_ssl | max_latency_ms | comment |
+--------------+---------------------------------------------------+------+-----------+--------+--------+-------------+-----------------+---------------------+---------+----------------+---------+
| 11           | cluster1-pxc-2.cluster1-pxc.pxc.svc.cluster.local | 3306 | 0         | ONLINE | 1000   | 0           | 1000            | 0                   | 1       | 0              |         |
| 12           | cluster1-pxc-0.cluster1-pxc.pxc.svc.cluster.local | 3306 | 0         | ONLINE | 1000   | 0           | 1000            | 0                   | 1       | 0              |         |
| 12           | cluster1-pxc-1.cluster1-pxc.pxc.svc.cluster.local | 3306 | 0         | ONLINE | 1000   | 0           | 1000            | 0                   | 1       | 0              |         |
| 10           | cluster1-pxc-1.cluster1-pxc.pxc.svc.cluster.local | 3306 | 0         | ONLINE | 1000   | 0           | 1000            | 0                   | 1       | 0              |         |
| 10           | cluster1-pxc-0.cluster1-pxc.pxc.svc.cluster.local | 3306 | 0         | ONLINE | 1000   | 0           | 1000            | 0                   | 1       | 0              |         |
+--------------+---------------------------------------------------+------+-----------+--------+--------+-------------+-----------------+---------------------+---------+----------------+---------+
```
Also first you mention one node cluster, but then later mention 3 PXC nodes and deleting one of them creates the issue.
It would be helpful if you provided clear info on how to reproduce your issue (environment, number of nodes (pxc, proxysql, kubernetes) commands which show the issue) so that we can check if the PR is working correctly in all cases.

Thanks!

**Comment by pservit** [comment]
I see this on 1.3.0 version of operator:

```
mysql> select * from mysql_servers;
+--------------+--------------+------+-----------+--------------+--------+-------------+-----------------+---------------------+---------+----------------+---------+
| hostgroup_id | hostname     | port | gtid_port | status       | weight | compression | max_connections | max_replication_lag | use_ssl | max_latency_ms | comment |
+--------------+--------------+------+-----------+--------------+--------+-------------+-----------------+---------------------+---------+----------------+---------+
| 11           | 10.42.7.30   | 3306 | 0         | ONLINE       | 1000   | 0           | 1000            | 0                   | 0       | 0              |         |
| 12           | 10.42.10.178 | 3306 | 0         | ONLINE       | 1000   | 0           | 1000            | 0                   | 0       | 0              |         |
| 10           | 10.42.10.178 | 3306 | 0         | ONLINE       | 1000   | 0           | 1000            | 0                   | 0       | 0              |         |
| 11           | 10.42.5.40   | 3306 | 0         | OFFLINE_HARD | 1000   | 0           | 1000            | 0                   | 0       | 0              |         |
+--------------+--------------+------+-----------+--------------+--------+-------------+-----------------+---------------------+---------+----------------+---------+
4 rows in set (0.00 sec)
```

**Comment by hors** [comment]
@pservit src/peer-list.go was moved into https://github.com/percona/percona-xtradb-cluster-operator/tree/master/cmd/peer-list repo. Could you please re-create the PR. 
P.S. sorry for inconvenience.

**Comment by pservit** [comment]
done
https://github.com/percona/percona-xtradb-cluster-operator/pull/419

**Pull request closed without merging**
